#!/usr/bin/env python3
# Copyright 2026 Honu Robotics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Write a world that lays out every part macro as its own model.

This is the review world for the URDF side of the catalog: each
urdf/<part>.urdf.xacro is instantiated alone (the macro as root link),
expanded, converted to SDF the way Gazebo would convert the assembled
vehicle, and placed on a grid. Open it and toggle collisions, inertia and
center of mass from the entity menu to check each part against its mesh.

Needs a sourced workspace where bluerobotics_parts is installed, because
the macros resolve $(find bluerobotics_parts):

    ros2 run bluerobotics_parts parts_check_world.py --out worlds/parts_check.sdf
    gz sim worlds/parts_check.sdf
"""

import argparse
import pathlib
import re
import subprocess
import sys
import tempfile

SPACING = 1.6
COLUMNS = 5
HEIGHT = 0.8

PROBE = """<?xml version="1.0"?>
<robot name="{part}" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find bluerobotics_parts)/urdf/parts.xacro"/>
  <xacro:{part} name="{part}" parent=""/>
</robot>
"""

WORLD_HEAD = """<?xml version="1.0"?>
<!-- GENERATED by scripts/parts_check_world.py: every part macro as its own
     static model, for reviewing inertia, collisions and visuals against the
     mesh. Right click a model > View > Collisions / Inertia / Center of Mass.
     Regenerate after an import. -->
<sdf version="1.9">
  <world name="parts_check">
    <physics name="1ms" type="ode">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <scene>
      <ambient>0.5 0.5 0.5 1</ambient>
      <background>0.6 0.72 0.85 1</background>
      <grid>true</grid>
    </scene>
    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.4 0.3 -0.85</direction>
    </light>
    <model name="ground">
      <static>true</static>
      <link name="link">
        <visual name="v">
          <geometry><plane><normal>0 0 1</normal><size>20 20</size></plane></geometry>
          <material><ambient>0.45 0.5 0.55 1</ambient><diffuse>0.45 0.5 0.55 1</diffuse></material>
        </visual>
      </link>
    </model>
"""

WORLD_TAIL = """  </world>
</sdf>
"""


def part_model(part, tmp):
    probe = tmp / f'{part}.urdf.xacro'
    probe.write_text(PROBE.format(part=part))
    urdf = subprocess.run(['xacro', str(probe)], check=True, capture_output=True, text=True).stdout
    urdf_path = tmp / f'{part}.urdf'
    urdf_path.write_text(urdf)
    sdf = subprocess.run(['gz', 'sdf', '-p', str(urdf_path)], check=True,
                         capture_output=True, text=True).stdout
    match = re.search(r'<model .*?</model>', sdf, re.S)
    if not match:
        raise RuntimeError(f'{part}: no model in converted SDF:\n{sdf[:400]}')
    return match.group(0)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--urdf-dir', help='directory holding the part macros '
                    '(default: the installed share/bluerobotics_parts/urdf)')
    ap.add_argument('--out', required=True, help='world file to write')
    args = ap.parse_args(argv)

    if args.urdf_dir:
        urdf_dir = pathlib.Path(args.urdf_dir)
    else:
        share = subprocess.run(['ros2', 'pkg', 'prefix', '--share', 'bluerobotics_parts'],
                               check=True, capture_output=True, text=True).stdout.strip()
        urdf_dir = pathlib.Path(share) / 'urdf'
    parts = sorted(p.name[:-len('.urdf.xacro')] for p in urdf_dir.glob('*.urdf.xacro')
                   if p.name not in ('part_probe.urdf.xacro',))
    if not parts:
        sys.exit(f'no part macros in {urdf_dir}')

    chunks = [WORLD_HEAD]
    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        for i, part in enumerate(parts):
            model = part_model(part, tmp)
            x = (i % COLUMNS) * SPACING - (COLUMNS - 1) * SPACING / 2
            y = -(i // COLUMNS) * SPACING
            opening = f"<model name='{part}'>"  # noqa: Q000 the SDF uses single quotes
            model = model.replace(
                opening,
                opening + f'\n      <static>true</static>\n'
                f'      <pose>{x:.2f} {y:.2f} {HEIGHT} 0 0 0</pose>', 1)
            chunks.append('    ' + model.replace('\n', '\n    ').rstrip() + '\n')
            print(f'{part:34s} at ({x:+.1f}, {y:+.1f})')
    chunks.append(WORLD_TAIL)
    pathlib.Path(args.out).write_text(''.join(chunks))
    print(f'{len(parts)} parts -> {args.out}')


if __name__ == '__main__':
    main()
